# use the xterm-256color terminal
set -g default-terminal "screen-256color"

# apply Tc
set-option -ga terminal-overrides ",xterm-256color:Tc"

# shell
# set-option -g default-shell /usr/local/bin/fish
set-option -g default-shell /opt/homebrew/bin/fish

# mouse
set -g mouse on

# clipboard integration
set -g set-clipboard

# window title
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# current window title background color
setw -g window-status-current-style bg=colour190

# border color
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour190,bg=default
set -g pane-border-lines double  # single double heavy simple number
set -g pane-border-status top
set -g pane-border-indicators arrows


# binds for pane
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# short cuts to select pane
bind-key -n C-S-End display-panes -d 500
bind-key -n C-S-Up select-pane -U \; display-panes -d 250
bind-key -n C-S-Down select-pane -D \; display-panes -d 250
bind-key -n C-S-Right select-pane -R \; display-panes -d 250
bind-key -n C-S-Left select-pane -L \; display-panes -d 250

# short cuts to select window
bind-key -n S-M-Up select-window -p \; display-panes -d 250
bind-key -n S-M-Down select-window -n \; display-panes -d 250
bind-key -n S-M-Right select-window -n \; display-panes -d 250
bind-key -n S-M-Left select-window -p \; display-panes -d 250
bind-key -n S-Up select-window -p \; display-panes -d 250
bind-key -n S-Down select-window -n \; display-panes -d 250

# broadcast on/off
bind a setw synchronize-panes
setw -g window-status-format         '#{?pane_synchronized,#[bg=magenta],}#I:#W'
setw -g window-status-current-format '#{?pane_synchronized,#[bg=fuchsia],}#I:#W'

# plugins

## thumbs (https://github.com/fcsonline/tmux-thumbs)
set -g @thumbs-key v
set -g @thumbs-command 'echo -n {} | tmux load-buffer -bxclip -; tmux paste-buffer -bxclip -d'
run-shell ~/.tmux/plugins/tmux-thumbs/tmux-thumbs.tmux
set -g @thumbs-upcase-command 'echo -n {} | pbcopy'
set -g @thumbs-unique enabled
set -g @thumbs-position right
set -g @thumbs-bg-color blue
set -g @thumbs-regexp-1 '([A-Za-z0-9/\._-]+:[1-9][0-9]+:[1-9][0-9]+)' # file.ext:line:column
set -g @thumbs-regexp-2 '([A-Za-z0-9/\._-]+:[1-9][0-9]+)' # file.ext:line

## fingers (https://github.com/Morantron/tmux-fingers)
run-shell ~/.tmux/plugins/tmux-fingers/tmux-fingers.tmux
set -g @fingers-main-action "xargs code"

# Set the control character to Ctrl+Spacebar (instead of Ctrl+B)
set -g prefix C-space
unbind-key C-b
bind-key C-space send-prefix

# Set new panes to open in current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Set new windows to also open in current directory
bind c new-window -c "#{pane_current_path}"

# Set more intuitive window split shortcut
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Fade unfocused panes out
set -g window-style fg=colour242
set -g window-active-style fg=colour246

bind-key -T copy-mode C-B send-keys -X begin-selection
bind-key -T copy-mode Enter send-keys -X copy-selection

bind l send-keys -R

# Swap adjacent windows
bind-key -n S-PageUp swap-window -t -1 \; select-window -t -1
bind-key -n S-PageDown swap-window -t +1 \; select-window -t +1
